package org.smbc.datadiff.report;

import org.smbc.datadiff.model.ComparisonSummary;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

/** Orchestrates the HTML report renderers without owning presentation details. */
public class HtmlReportGenerator implements ReportGenerator {
    private final StyleRenderer styleRenderer;
    private final HeaderRenderer headerRenderer;
    private final SummaryRenderer summaryRenderer;
    private final FileResultRenderer fileResultRenderer;

    public HtmlReportGenerator() {
        this(new StyleRenderer(), new HeaderRenderer(), new SummaryRenderer(), new FileResultRenderer());
    }

    public HtmlReportGenerator(StyleRenderer styleRenderer, HeaderRenderer headerRenderer,
                               SummaryRenderer summaryRenderer, FileResultRenderer fileResultRenderer) {
        this.styleRenderer = styleRenderer;
        this.headerRenderer = headerRenderer;
        this.summaryRenderer = summaryRenderer;
        this.fileResultRenderer = fileResultRenderer;
    }

    @Override
    public void generate(ComparisonSummary summary, Path reportFile) {
        if (summary == null) throw new IllegalArgumentException("Comparison summary cannot be null");
        if (reportFile == null) throw new IllegalArgumentException("Report file cannot be null");
        try {
            Path reportDirectory = reportFile.getParent();
            if (reportDirectory != null) Files.createDirectories(reportDirectory);
            Files.writeString(reportFile, buildHtml(summary), StandardCharsets.UTF_8);
        } catch (IOException exception) {
            throw new IllegalStateException("Unable to generate HTML report: " + reportFile, exception);
        }
    }

    private String buildHtml(ComparisonSummary summary) {
        StringBuilder html = new StringBuilder();
        styleRenderer.append(html);
        headerRenderer.append(html);
        summaryRenderer.append(html, summary);
        fileResultRenderer.appendAll(html, summary);
        html.append("""
                <div class="footer">
                    Generated by Data Reconciliation Utility
                </div>
                </div>
                </body>
                </html>
                """);
        return html.toString();
    }
}
